name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:        

env:
  REGISTRY: ghcr.io

permissions:
  actions: read
  contents: write
  packages: write

jobs:
  lint-test-build-affected:
    name: Lint, Test & Build
    if: >
      !startsWith(github.event.head_commit.message, 'chore') &&
      !startsWith(github.event.head_commit.message, 'docs') &&
      !startsWith(github.event.head_commit.message, 'ci')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          go_version: 1.24.x
          node_version: 24.x

      - name: Lint, test and build
        run: |
          pnpm nx affected --target=lint --parallel=3
          pnpm nx affected --target=biome-lint --parallel=3
          pnpm nx run-many --all --target=test --parallel=3 --exclude=e2e
          pnpm nx affected --target=build --parallel=3

  e2e-tests:
    name: Run E2E Tests
    if: >
      github.event_name == 'workflow_dispatch' ||
      startsWith(github.event.head_commit.message, 'fix') ||
      startsWith(github.event.head_commit.message, 'feat')
    needs: [lint-test-build-affected]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: 24.x

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Free disk space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          docker system prune -af || true
          df -h    

      # - name: Set up Docker
      #   uses: docker/setup-docker-action@v4

      # - name: Set up Docker Compose
      #   uses: docker/setup-compose-action@v1

      # - name: Start Docker Compose
      #   run: pnpm nx up-ci e2e -d

      - name: Run E2E Tests
        run: pnpm nx test e2e --reporter=list        

  version-and-tag:
    name: Version and Tag
    if: >
      github.event_name == 'workflow_dispatch' ||
      startsWith(github.event.head_commit.message, 'fix') ||
      startsWith(github.event.head_commit.message, 'feat')
    needs: [lint-test-build-affected, e2e-tests]
    runs-on: ubuntu-latest 
    concurrency:
      group: release-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: 24.x

      - name: Set Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Show affected
        run: echo ${{ matrix.frontend_affected_paths }}

      - name: Run NX release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm nx release --skip-publish --groups=frontend,backend
